---
- hosts: ubuntu
  gather_facts: yes
  become: true
  tasks:
  - name: Update packages
    apt:
      update_cache: yes
  - name: Upgrade packages
    apt:
      upgrade: full
  - name: Install hostapd and dnsmasq
    apt:
      name: hostapd
      state: present
    register: hostapd_out
  - name: Install hostapd and dnsmasq
    apt:
      name: dnsmasq
      state: present
    register: dnsmasq_out
  - debug: var=hostapd_out
  - debug: var=dnsmasq_out
#  - name: Stop the services
#    service:
#      name: "{{ item }}"
#      state:
#    with_items:
#    - hostapd
#    - dnsmasq
  - name: Configure static IP
    copy:
#    lineinfile:
      dest: /etc/dhcpcd.conf
      content: "{{ item }}"
#      line: "{{ item }}"
    with_items:
    - interface wlan0
    - static ip_address=192.168.0.10/24
    - denyinterfaces eth0
    - denyinterfaces wlan0
  - name: Rename the original dnsmasq.conf file
    shell: mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
  - name: Create a new dnsmasq.conf file
    copy:
#    lineinfile:
      dest: /etc/dnsmasq.conf
      content: "{{ item }}"
#      line: "{{ item }}"
    with_items:
    - interface=wlan0
    - '  dhcp-range=192.168.0.11,192.168.0.30,255.255.255.0,24h'
  - name: Configure the access point host software
    copy:
#    lineinfile:
      dest: /etc/hostapd/hostapd.conf
      content: "{{ item }}"
#      line: "{{ item }}"
    with_items:
    - interface=wlan0
    - bridge=br0
    - hw_mode=g
    - channel=7
    - wmm_enabled=0
    - macaddr_acl=0
    - auth_algs=1
    - ignore_broadcast_ssid=0
    - wpa=2
    - wpa_key_mgmt=WPA-PSK
    - wpa_pairwise=TKIP
    - rsn_pairwise=CCMP
    - ssid=NETWORK
    - wpa_passphrase=PASSWORD
  - name: Set the location of the conf file
    lineinfile:
      dest: /etc/default/hostapd
      line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  - name: Set up traffic forwarding
    lineinfile:
      dest: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'
  - name: Add new iptables rule
    shell: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  - name: Save the new iptables rule
    shell: sh -c "iptables-save > /etc/iptables.ipv4.nat"
  - name: Edit the /etc/rc.local file to load the iptable rules on boot
    lineinfile:
      dest: /etc/rc.local
      insertbefore: 'exit 0'
      line: 'iptables-restore < /etc/iptables.ipv4.nat'
  - name: Install bridge-utils
    apt:
      name: 'bridge-utils'
      state: present
  - name: Add a new bridge
    shell: brctl addbr br0
  - name: Connect eth0 interface to bridge
    shell: brctl addif br0 eth0
  - name: Edit the interface file
    lineinfile:
      dest: /etc/network/interfaces
      line: "{{ item }}"
    with_items:
    - auto br0
    - iface br0 inet manual
    - bridge_ports eth0 wlan0
  - name: Reboot server and wait for its restart
    reboot:
      reboot_timeout: 3600

