---

- name: Install host dependencies
  pacman:
    name:
      - python-docker
      - python-dnspython
    state: latest
    update_cache: yes

- name: Ensure Docker is installed
  pacman:
    name:
      - docker
    state: latest
  when: matrix_docker_installation_enabled|bool
